// Mocks generated by Mockito 5.4.5 from annotations
// in flower_e_commerce/test/features/auth/domain/usecase/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_e_commerce/core/utils/api_result/api_result.dart' as _i5;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/forget_password_request.dart'
    as _i9;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/reset_password_request.dart'
    as _i13;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/verfiy_password_request.dart'
    as _i11;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/forget_password_response.dart'
    as _i8;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/reset_password_responsea.dart'
    as _i12;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/verfiy_password_response.dart'
    as _i10;
import 'package:flower_e_commerce/features/auth/data/repository/auth_repository_imp.dart'
    as _i3;
import 'package:flower_e_commerce/features/auth/data/source/auth_remote_data_source.dart'
    as _i2;
import 'package:flower_e_commerce/features/auth/domain/entity/login_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepositoryImp].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryImp extends _i1.Mock implements _i3.AuthRepositoryImp {
  MockAuthRepositoryImp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRemoteDataSource get authRemoteDataSource => (super.noSuchMethod(
        Invocation.getter(#authRemoteDataSource),
        returnValue: _FakeAuthRemoteDataSource_0(
          this,
          Invocation.getter(#authRemoteDataSource),
        ),
      ) as _i2.AuthRemoteDataSource);

  @override
  set authRemoteDataSource(_i2.AuthRemoteDataSource? _authRemoteDataSource) =>
      super.noSuchMethod(
        Invocation.setter(
          #authRemoteDataSource,
          _authRemoteDataSource,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ApiResult<_i6.LoginModel>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i6.LoginModel>>.value(
            _i7.dummyValue<_i5.ApiResult<_i6.LoginModel>>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.LoginModel>>);

  @override
  _i4.Future<_i5.ApiResult<_i8.ForgetPasswordResponse>> forgetPassword(
          _i9.ForgetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i8.ForgetPasswordResponse>>.value(
                _i7.dummyValue<_i5.ApiResult<_i8.ForgetPasswordResponse>>(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i8.ForgetPasswordResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i10.VerfiyPasswordResponse>> verfiyPassword(
          _i11.VerfiyPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verfiyPassword,
          [request],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i10.VerfiyPasswordResponse>>.value(
                _i7.dummyValue<_i5.ApiResult<_i10.VerfiyPasswordResponse>>(
          this,
          Invocation.method(
            #verfiyPassword,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i10.VerfiyPasswordResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i12.ResetPasswordResponsea>> resetPassword(
          _i13.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i12.ResetPasswordResponsea>>.value(
                _i7.dummyValue<_i5.ApiResult<_i12.ResetPasswordResponsea>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i12.ResetPasswordResponsea>>);
}
