sonar.projectKey=MahmoodEbrahim_flower_e_commerce
sonar.organization=mahmoodebrahim

# Displayed in the SonarCloud UI
sonar.projectName=flower_e_commerce

sonar.projectVersion=1.0
# Source and test directories
sonar.sources=lib
sonar.tests=test

# Exclusions (ignore generated, platform-specific, or mock code)
sonar.exclusions=**/build/**,**/ios/**,**/android/**,**/web/**,**/macos/**,lib/**/*.g.dart,**/mock/**,**/*mock*.*


# Encoding of the source code
sonar.sourceEncoding=UTF-8
