// Mocks generated by Mockito 5.4.5 from annotations
// in flower_e_commerce/test/features/auth/api/source/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_e_commerce/features/auth/api/client/auth_api_service.dart'
    as _i3;
import 'package:flower_e_commerce/features/auth/api/models/auth_response/auth_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseDto_0 extends _i1.SmartFake
    implements _i2.AuthResponseDto {
  _FakeAuthResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i3.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponseDto> logIn(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [body],
        ),
        returnValue:
            _i4.Future<_i2.AuthResponseDto>.value(_FakeAuthResponseDto_0(
          this,
          Invocation.method(
            #logIn,
            [body],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponseDto>);
}
