// Mocks generated by Mockito 5.4.5 from annotations
// in flower_e_commerce/test/features/auth/api/source/auth_remote_data_souce_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flower_e_commerce/features/auth/api/client/auth_api_service.dart'
    as _i6;
import 'package:flower_e_commerce/features/auth/api/models/auth_response/auth_response_dto.dart'
    as _i2;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/forget_password_request.dart'
    as _i8;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/reset_password_request.dart'
    as _i10;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/request/verfiy_password_request.dart'
    as _i9;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/forget_password_response.dart'
    as _i3;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/reset_password_responsea.dart'
    as _i5;
import 'package:flower_e_commerce/features/auth/api/models/forget_password/response/verfiy_password_response.dart'
    as _i4;
import 'package:flower_e_commerce/features/auth/api/models/signup_request/signup_request_dto.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseDto_0 extends _i1.SmartFake
    implements _i2.AuthResponseDto {
  _FakeAuthResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerfiyPasswordResponse_2 extends _i1.SmartFake
    implements _i4.VerfiyPasswordResponse {
  _FakeVerfiyPasswordResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponsea_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponsea {
  _FakeResetPasswordResponsea_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i6.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthResponseDto> logIn(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [body],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseDto>.value(_FakeAuthResponseDto_0(
          this,
          Invocation.method(
            #logIn,
            [body],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseDto>);

  @override
  _i7.Future<_i3.ForgetPasswordResponse> forgetPassword(
          _i8.ForgetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i7.Future<_i3.ForgetPasswordResponse>.value(
            _FakeForgetPasswordResponse_1(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.ForgetPasswordResponse>);

  @override
  _i7.Future<_i4.VerfiyPasswordResponse> verfiyPassword(
          _i9.VerfiyPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verfiyPassword,
          [request],
        ),
        returnValue: _i7.Future<_i4.VerfiyPasswordResponse>.value(
            _FakeVerfiyPasswordResponse_2(
          this,
          Invocation.method(
            #verfiyPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.VerfiyPasswordResponse>);

  @override
  _i7.Future<_i5.ResetPasswordResponsea> resetPassword(
          _i10.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i7.Future<_i5.ResetPasswordResponsea>.value(
            _FakeResetPasswordResponsea_3(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.ResetPasswordResponsea>);

  @override
  _i7.Future<_i2.AuthResponseDto> signUp(_i11.SignupRequestDto? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [body],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseDto>.value(_FakeAuthResponseDto_0(
          this,
          Invocation.method(
            #signUp,
            [body],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseDto>);
}
